# See [Source Acceptance Tests](https://docs.airbyte.io/connector-development/testing-connectors/source-acceptance-tests-reference)
# for more information about how to configure these tests
# The line below is commented out to skip the test `test_state_with_abnormally_large_values`
# as a temporary solution not to block publishing of new versions:
# future_state_path: "integration_tests/abnormal_state.json"
connector_image: airbyte/source-google-analytics-v4:dev
tests:
  spec:
    - spec_path: "source_google_analytics_v4/spec.json"
  connection:
    - config_path: "secrets/service_config.json"
      status: "succeed"
    - config_path: "secrets/old_config.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
  discovery:
    - config_path: "secrets/service_config.json"
  basic_read:
    - config_path: "secrets/service_config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      empty_streams: []
  incremental:
    - config_path: "secrets/service_config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      # future_state_path: "integration_tests/abnormal_state.json"
  full_refresh:
    - config_path: "secrets/service_config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
